### ISSUE TITLE
Add minimum requirements

### ISSUE THREAD

**Issue by mhhennig** [martinosorb/herding-spikes#8]
State package requirements and minimum version numbers. The detection code seems to require python 2.7.10 or higher (not ported to python 3 yet).

**Comment by martinosorb** [comment]
I'll have a look and see if it's possible to port it to python3 without too much hassle.

**Comment by mhhennig** [comment]
It is mainly print() and possibly a few zip objects that have to be turned back into tuple().

**Comment by martinosorb** [comment]
I changed all the print() calls, currently it gives no syntax errors on python3. I'm going to try running it if I have a suitable dataset.
